
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package TP1.Java.src.main.java;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int PG = 7;
  public static final int IDENT = 13;
  public static final int PD = 8;
  public static final int MOD = 6;
  public static final int MOINS_UNAIRE = 14;
  public static final int SEMI = 9;
  public static final int EQUAL = 10;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int ENTIER = 12;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final int MOINS = 3;
  public static final int LET = 11;
  public static final int MUL = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MOINS",
  "MUL",
  "DIV",
  "MOD",
  "PG",
  "PD",
  "SEMI",
  "EQUAL",
  "LET",
  "ENTIER",
  "IDENT",
  "MOINS_UNAIRE"
  };
}

